finopsfoundation/focus_converters

focus_converter_base/focus_converter/conversion_configs/azure/D001_S009.yaml
=> Addion of Azure provider field

focus_converter_base/focus_converter/conversion_configs/oci/D011_S001.yaml
Added OCI Provider dimension (issue: #85)
=> Add OCI Provider dimension

focus_converter_base/focus_converter/conversion_configs/oci/D007_S001.yaml
Added OCI Region dimension (issue: #86)
=> Added OCI Region dimension

focus_converter_base/focus_converter/conversion_configs/oci/D002_S001.yaml
Added OCI Billing Account Id dimension (issue: #29)
=> Added OCI Billing Account Id dimension

focus_converter_base/focus_converter/conversion_configs/azure/D012_S001.yaml
=> add resourcename field from azure config

focus_converter_base/focus_converter/conversion_configs/azure/D011_S001.yaml
=> add billingcurrency field from azure config

focus_converter_base/focus_converter/conversion_configs/azure/D002_S001.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D002_S002.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D002_S003.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D003_S001.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D003_S002.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D003_S003.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D004_S001.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D004_S002.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D004_S003.yaml
Converted 3 Azure fields to datetime data type.
=> converted all date fields to datetime

focus_converter_base/focus_converter/data_loaders/data_loader.py
=> Hotfix: Added ignore_errors while reading cvs to allow reading even if the csv parsing fails.

focus_converter_base/focus_converter/conversion_configs/oci/D001_S001.yaml, focus_converter_base/focus_converter/conversion_configs/oci/D003_S001.yaml, focus_converter_base/focus_converter/conversion_configs/oci/D004_S001.yaml, focus_converter_base/focus_converter/conversion_configs/oci/D005_S001.yaml, focus_converter_base/focus_converter/conversion_configs/oci/D006_S001.yaml
Added multiple OCI focus v0.5 dimensions:  
- AvailabilityZone (issue #82), 
- BillingCurrency (issue #83), 
- ResourceId (issue #56), 
- ServiceName (issue #88), 
- SubAccountId (issue #89)
=> Added multiple OCI focus v0.5 dimensions:  AvailabilityZone, BillingCurrency, ResourceId, ServiceName, SubAccountId

focus_converter_base/focus_converter/conversion_configs/oci/D008_S001.yaml, focus_converter_base/focus_converter/conversion_configs/oci/D009_S001.yaml
Added OCI BilledCost (issue #35) and EffectiveCost (issue #90)
=> Added OCI BilledCost (issue #35) and EffectiveCost (issue #90)

focus_converter_base/focus_converter/conversion_configs/azure/D0017_S001.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D017_S002.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D017_S003.yaml
=> Create ChargePeriodStart FOCUS column from Billing Start

focus_converter_base/focus_converter/conversion_configs/azure/D016_S001.yaml
=> addition of Publisher field for Azure provider.

focus_converter_base/focus_converter/conversion_configs/azure/D015_S001.yaml
=> addition of BilledCost field

focus_converter_base/focus_converter/conversion_configs/azure/D013_S001.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D014_S001.yaml
=> addition of Billing Account Name and Billing Account ID fields

.github/workflows/lint.yaml, .github/workflows/python_version_check.yaml, .github/workflows/unittest.yaml, focus_converter_base/focus_converter/configs/base_config.py, focus_converter_base/focus_converter/conversion_functions/column_functions.py, focus_converter_base/focus_converter/converter.py, focus_converter_base/pyproject.toml, focus_converter_base/tests/converter_functions/test_connected_nodes.py, focus_converter_base/tests/converter_functions/test_datetime_import_from_csv.py, focus_converter_base/tests/converter_functions/test_lookup_function.py
Makes jupyertal optional dependencies.
Fixed build for windows and mac os.
=> Build fixes.

focus_converter_base/focus_converter/conversion_configs/aws-cur/0_dimension_dtypes_S001.yaml, focus_converter_base/focus_converter/conversion_configs/aws/0_dimension_dtypes_S001.yaml
Added support for lineItem/ResourceId column in the rules when it's not present in source data.
=> Handle lineItem/ResourceId if it is missing in source data

.github/workflows/lint.yaml, focus_converter_base/focus_converter/data_loaders/data_loader.py, focus_converter_base/focus_converter/main.py, focus_converter_base/focus_converter/utils/export_conversion_rules.py, focus_converter_base/pyproject.toml
Several small clean ups and additional validation.
1) Added flake8 to the lint check to align with focus_validator. 
2) Cleaned up files failing flake8 evaluations except C type as there were two classes with particular cyclomatic complexity.
3) Updated focus_converter_base/pyproject.toml to include logging in pytest execution by default
=> Adding flake8 config for higher quality code.

focus_converter_base/focus_converter/conversion_configs/azure/D019_S001.yaml
=> addition of availability zone field

focus_converter_base/focus_converter/conversion_configs/azure/D020_S001.yaml
=> addition of focus column ChargeDescription

focus_converter_base/focus_converter/conversion_configs/azure/D022_S001.yaml, focus_converter_base/focus_converter/models/focus_column_names.py
=> addition of focus column PricingCategory

focus_converter_base/focus_converter/conversion_configs/azure/D021_S001.yaml
=> addition of focus column ChargeFrequency

focus_converter_base/focus_converter/conversion_configs/azure/D023_S001.yaml
=> addition of ChargeSubcategory

focus_converter_base/focus_converter/conversion_configs/azure/D029_S001.yaml
=> Addition of InvoiceIssuer FOCUS field.

focus_converter_base/focus_converter/configs/base_config.py, focus_converter_base/focus_converter/conversion_configs/azure/0_dimension_dtypes_S001.yaml, focus_converter_base/focus_converter/conversion_configs/azure/D030_S001.yaml, focus_converter_base/focus_converter/conversion_functions/column_functions.py
=> Addition of UsageUnit FOCUS field via Pricing Units mapping.

focus_converter_base/focus_converter/conversion_configs/azure/D031_S001.yaml
=> Addition of SkuPriceId FOCUS field, defaulting to null.

focus_converter_base/focus_converter/conversion_configs/azure/mapping_files/azure_category_mapping.csv
Remove a duplicate `microsoft.security,Security` mapping for Azure.
=> Remove duplicate Azure microsoft.security mapping

focus_converter_base/focus_converter/conversion_configs/azure/D026_S001.yaml
=> addition of CommitmentDiscountType

focus_converter_base/focus_converter/conversion_configs/azure/D024_S001.yaml
=> addition of CommitmentDiscountCategory

focus_converter_base/focus_converter/conversion_configs/azure/D033_S001.yaml, focus_converter_base/focus_converter/models/focus_column_names.py
=> addition of ChargeCategory column.

focus_converter_base/focus_converter/common/cli_options.py, focus_converter_base/focus_converter/data_loaders/data_exporter.py, focus_converter_base/focus_converter/main.py
Created new CLI option for --export-format csv
=> Added support for file CSV export
